// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAai3TcTKb3ZGp54dJvIkBkluCaUAXZ5HE',
    appId: '1:817558497715:web:193cbfff556a357b5503c6',
    messagingSenderId: '817558497715',
    projectId: 'parmacy-app',
    authDomain: 'parmacy-app.firebaseapp.com',
    storageBucket: 'parmacy-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJtLf-jIuBG7b16xN-OvzaAtgnkGWi_-M',
    appId: '1:817558497715:android:1a90d9dc5a8502f35503c6',
    messagingSenderId: '817558497715',
    projectId: 'parmacy-app',
    storageBucket: 'parmacy-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbdq8EvDXaMOseHEVU_JWKAD9roYo0s2s',
    appId: '1:817558497715:ios:eecfb044e18d54885503c6',
    messagingSenderId: '817558497715',
    projectId: 'parmacy-app',
    storageBucket: 'parmacy-app.appspot.com',
    iosClientId: '817558497715-376m5ski6vretbcs37cb6kgfnga6d8iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmacyHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbdq8EvDXaMOseHEVU_JWKAD9roYo0s2s',
    appId: '1:817558497715:ios:eecfb044e18d54885503c6',
    messagingSenderId: '817558497715',
    projectId: 'parmacy-app',
    storageBucket: 'parmacy-app.appspot.com',
    iosClientId: '817558497715-376m5ski6vretbcs37cb6kgfnga6d8iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmacyHealthApp',
  );
}
